[[redirects]]
  from = "/devis"
  to = "/pages/devis.html"
  status = 200
  force = true

[[redirects]]
  from = "/contact"
  to = "/pages/contact.html"
  status = 200
  force = true

[[redirects]]
  from = "/confirmation"
  to = "/pages/confirmation.html"
  status = 200
  force = true